/* =====================================================
   Exportación del esquema de la base (estructura)

   Lee el catálogo de PostgreSQL y devuelve sentencias para recrear
   las tablas desde cero. Así un respaldo no depende de que exista un
   archivo de esquema aparte: es autosuficiente.

   Orden de restauración: tablas -> datos -> restricciones -> índices
   (cargar los datos antes de las claves foráneas evita problemas de orden).
===================================================== */

function identificador(nombre) {

    return `"${String(nombre).replace(/"/g, '""')}"`;
}


async function exportarEsquema(client) {

    const advertencias = [];

    const { rows: tablas } = await client.query(`
        SELECT c.oid, c.relname AS nombre
        FROM pg_class c
        INNER JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind IN ('r', 'p')
        ORDER BY c.relname
    `);

    const salida = [];

    for (const tabla of tablas) {

        const { rows: columnas } = await client.query(
            `
            SELECT
                a.attname AS nombre,
                format_type(a.atttypid, a.atttypmod) AS tipo,
                a.attnotnull AS no_nulo,
                pg_get_expr(d.adbin, d.adrelid) AS valor,
                a.attidentity AS identidad,
                a.attgenerated AS generada
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d
                ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = $1
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            `,
            [tabla.oid]
        );

        const definiciones = columnas.map(col => {

            if (col.generada) {
                advertencias.push(`columna generada ${tabla.nombre}.${col.nombre}: se restaura como columna común`);
            }

            let definicion = `${identificador(col.nombre)} `;

            const esSerial =
                col.valor &&
                /^nextval\(/i.test(col.valor) &&
                ["integer", "bigint", "smallint"].includes(col.tipo);

            if (col.identidad) {

                definicion += `${col.tipo} GENERATED BY DEFAULT AS IDENTITY`;

            } else if (esSerial) {

                definicion += col.tipo === "bigint"
                    ? "BIGSERIAL"
                    : col.tipo === "smallint" ? "SMALLSERIAL" : "SERIAL";

            } else {

                definicion += col.tipo;

                if (col.valor && !col.generada) {
                    definicion += ` DEFAULT ${col.valor}`;
                }
            }

            if (col.no_nulo) {
                definicion += " NOT NULL";
            }

            return definicion;
        });

        const secuencias = columnas
            .filter(col => col.identidad || (col.valor && /^nextval\(/i.test(col.valor)))
            .map(col => ({ tabla: tabla.nombre, columna: col.nombre }));

        salida.push({
            nombre: tabla.nombre,
            ddl: `CREATE TABLE ${identificador(tabla.nombre)} (\n  ${definiciones.join(",\n  ")}\n)`,
            secuencias
        });
    }

    const { rows: restricciones } = await client.query(`
        SELECT
            c.conrelid::regclass::text AS tabla_texto,
            cl.relname AS tabla,
            c.conname AS nombre,
            c.contype AS tipo,
            pg_get_constraintdef(c.oid) AS definicion
        FROM pg_constraint c
        INNER JOIN pg_class cl ON cl.oid = c.conrelid
        WHERE c.connamespace = 'public'::regnamespace
          AND c.contype IN ('p', 'u', 'c', 'f')
        ORDER BY CASE c.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 ELSE 4 END, c.conname
    `);

    const nombresRestricciones = new Set(restricciones.map(r => r.nombre));

    const { rows: indices } = await client.query(`
        SELECT indexname AS nombre, indexdef AS definicion
        FROM pg_indexes
        WHERE schemaname = 'public'
        ORDER BY indexname
    `);

    // los índices que respaldan una restricción se recrean con la restricción
    const indicesPropios = indices.filter(i => !nombresRestricciones.has(i.nombre));

    const { rows: otros } = await client.query(`
        SELECT
            (SELECT COUNT(*)::int FROM pg_trigger t
                INNER JOIN pg_class c ON c.oid = t.tgrelid
                WHERE c.relnamespace = 'public'::regnamespace AND NOT t.tgisinternal) AS disparadores,
            (SELECT COUNT(*)::int FROM pg_views WHERE schemaname = 'public') AS vistas,
            (SELECT COUNT(*)::int FROM pg_proc p
                WHERE p.pronamespace = 'public'::regnamespace) AS funciones
    `);

    if (otros[0].disparadores || otros[0].vistas || otros[0].funciones) {
        advertencias.push(
            `la base tiene ${otros[0].disparadores} disparadores, ${otros[0].vistas} vistas y ` +
            `${otros[0].funciones} funciones que el respaldo no incluye`
        );
    }

    return {
        tablas: salida,
        restricciones: restricciones.map(r => ({
            tabla: r.tabla,
            nombre: r.nombre,
            tipo: r.tipo,
            sql: `ALTER TABLE ${identificador(r.tabla)} ADD CONSTRAINT ${identificador(r.nombre)} ${r.definicion}`
        })),
        indices: indicesPropios.map(i => i.definicion),
        advertencias
    };
}


module.exports = { exportarEsquema, identificador };
